# Matrizes

In [1]:
import numpy as np

In [3]:
matriz = np.array([[2,3,1],
                   [4,5,7]])
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [4]:
matriz.shape # retorna numero de linhas e colunas

(2, 3)

In [5]:
matriz[0]

array([2, 3, 1])

In [6]:
matriz[0][0]

2

In [7]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
